# Generated by Django 6.0.7 on 2026-07-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('distancia_plaza_metros', models.FloatField()),
                ('superficie_m2', models.FloatField()),
                ('flujo_personas_diario', models.IntegerField()),
                ('competencia_directa', models.IntegerField()),
                ('distancia_metro_metros', models.FloatField()),
                ('estacionamientos', models.IntegerField()),
                ('poblacion_radio_1km', models.IntegerField()),
                ('ingreso_promedio_hogar', models.IntegerField()),
                ('marketing_mensual', models.IntegerField()),
                ('trabajadores', models.IntegerField()),
                ('comuna', models.CharField(max_length=100)),
                ('tipo_negocio', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
                ('ventas_estimadas', models.FloatField()),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
